import random
from abc import ABC


class Generator(ABC):
    """
    Base class to all databases for random purposes.
    """
    _list: list[str]

    @classmethod
    def random(cls) -> str:
        return random.choice(cls._list)

    @classmethod
    def list(cls) -> list[str]:
        return cls._list


class Animal(Generator):
    """
    Database for animals names.
    """

    # _list: list[str] = ['aardvark', 'aardwolf', 'albatross', 'alligator', 'alpaca', 'anaconda', 'angelfish',
    #                     'anglerfish', 'ant', 'anteater', 'antelope', 'antlion', 'ape', 'aphid', 'armadillo', 'asp',
    #                     'aye-aye', 'baboon', 'badger', 'bandicoot', 'barnacle', 'barracuda', 'basilisk', 'bass',
    #                     'bat', 'bear', 'beaver', 'bedbug', 'bee', 'beetle', 'bird', 'bison', 'blackbird', 'blowfish',
    #                     'boa', 'boar', 'bob-cat', 'bobcat', 'bobolink', 'bonobo', 'booby', 'bovid', 'buck', 'budgie',
    #                     'buffalo', 'bug', 'bull', 'butterfly', 'buzzard', 'camel', 'canary', 'capybara', 'cardinal',
    #                     'caribou', 'carp', 'cat', 'caterpillar', 'catfish', 'catshark', 'cattle', 'centipede',
    #                     'cephalopod', 'chameleon', 'cheetah', 'chickadee', 'chicken', 'chihuahua', 'chimpanzee',
    #                     'chinchilla', 'chipmunk', 'chupacabra', 'cicada', 'clam', 'clownfish', 'cobra', 'cockatiel',
    #                     'cockatoo', 'cockroach', 'cod', 'coho', 'condor', 'constrictor', 'coral', 'cougar', 'cow',
    #                     'coyote', 'crab', 'crane', 'crawdad', 'crawfish', 'crayfish', 'cricket', 'crocodile', 'crow',
    #                     'cuckoo', 'dacshund', 'dalmation', 'damselfly', 'deer', 'dik-dik', 'dingo', 'dinosaur',
    #                     'dog', 'dolphin', 'donkey', 'dormouse', 'dove', 'dragon', 'dragonfly', 'drake', 'du-gong',
    #                     'duck', 'eagle', 'earthworm', 'earwig', 'echidna', 'eclectus', 'eel', 'egret', 'elephant',
    #                     'elk', 'emu', 'ermine', 'erne', 'falcon', 'ferret', 'finch', 'firefly', 'fish', 'flamingo',
    #                     'flatworm', 'flea', 'fly', 'flyingfish', 'fowl', 'fox', 'frog', 'galliform', 'gamefowl',
    #                     'gazelle', 'gecko', 'gerbil', 'gibbon', 'giraffe', 'gnat', 'goat', 'goldfish', 'goose',
    #                     'gopher', 'gorilla', 'grasshopper', 'groundhog', 'grouse', 'guan', 'guanaco', 'guineafowl',
    #                     'gull', 'guppy', 'haddock', 'halibut', 'hamster', 'hare', 'harrier', 'hawk', 'hedgehog',
    #                     'heron', 'herring', 'hippopotamus', 'hookworm', 'hornet', 'horse', 'hoverfly', 'hummingbird',
    #                     'hyena', 'hyrax', 'iguana', 'iguanodon', 'impala', 'inchworm', 'insect', 'jackal',
    #                     'jackrabbit', 'jaguar', 'jay', 'jellyfish', 'junglefowl', 'kangaroo', 'kingfisher', 'kite',
    #                     'kiwi', 'koala', 'koi', 'kookaburra', 'krill', 'ladybug', 'lama', 'lamb', 'lamprey',
    #                     'lancelet', 'lark', 'leech', 'lemming', 'lemur', 'leopard', 'leopon', 'lice', 'limpet',
    #                     'lion', 'lionfish', 'lizard', 'llama', 'lobster', 'locust', 'loon', 'louse', 'lungfish',
    #                     'lynx', 'macaw', 'mackerel', 'magpie', 'man-of-war', 'manatee', 'mandrill', 'mantis',
    #                     'marlin', 'marmoset', 'marmot', 'marsupials', 'mastodon', 'meadowlark', 'meerkat', 'mink',
    #                     'minnow', 'mite', 'mockingbird', 'mole', 'mollusk', 'mollusks', 'mongoose', 'monkey',
    #                     'moose', 'mosquito', 'moth', 'mouse', 'mule', 'muskox', 'muskrat', 'narwhal', 'nautilus',
    #                     'newt', 'nightingale', 'ocelot', 'octopus', 'opossum', 'orangutan', 'orca', 'osprey',
    #                     'ostrich', 'otter', 'owl', 'ox', 'panda', 'panther', 'parakeet', 'parrot', 'parrotfish',
    #                     'partridge', 'peacock', 'peafowl', 'pelican', 'penguin', 'perch', 'pheasant', 'pig',
    #                     'pigeon', 'pike', 'pinniped', 'piranha', 'planarian', 'platypus', 'pony', 'porcupine',
    #                     'porpoise', 'possum', 'prawn', 'ptarmigan', 'puffin', 'puma', 'python', 'quail', 'quelea',
    #                     'quetzal', 'quokka', 'rabbit', 'raccoon', 'rat', 'rattlesnake', 'raven', 'ray', 'reindeer',
    #                     'reptile', 'rhino', 'rhinoceros', 'ringworm', 'roadrunner', 'robin', 'rodent', 'rook',
    #                     'rooster', 'roundworm', 'sailfish', 'salamander', 'salmon', 'sandpiper', 'sawfish',
    #                     'scallop', 'scorpion', 'seahorse', 'seal', 'shark', 'sheep', 'shrew', 'shrimp', 'skink',
    #                     'skunk', 'skunks', 'sloth', 'slug', 'slugs', 'smelt', 'snail', 'snails', 'snake', 'snipe',
    #                     'sole', 'sparrow', 'spider', 'sponge', 'spoonbill', 'squid', 'squirrel', 'starfish',
    #                     'stingray', 'stoat', 'stork', 'sturgeon', 'swallow', 'swan', 'swift', 'swordfish',
    #                     'swordtail', 'tadpole', 'tahr', 'takin', 'tamarin', 'tapeworm', 'tapir', 'tarantula',
    #                     'tarpan', 'tarsier', 'termite', 'tern', 'terrapin', 'thrush', 'tick', 'tiger', 'tiglon',
    #                     'toad', 'tortoise', 'toucan', 'trout', 'tuna', 'turkey', 'turtle', 'tyrannosaurus', 'uakari',
    #                     'urchin', 'urial', 'urutu', 'velociraptor', 'vervet', 'vicuna', 'viper', 'vole', 'vulture',
    #                     'wallaby', 'walrus', 'warbler', 'warthog', 'wasp', 'weasel', 'weevil', 'whale', 'whippet',
    #                     'whitefish', 'whooper', 'wildcat', 'wildebeest', 'wolf', 'wolverine', 'wombat', 'woodchuck',
    #                     'woodpecker', 'wren', 'xerinae', 'yak', 'yeti', 'zander', 'zebra', 'zebu', 'zorilla']

    _list: list[str] = ['abelha', 'aranha', 'arara', 'águia', 'abutre', 'ácaro', 'anta', 'antílope', 'alce', 'anaconda',
                        'avestruz', 'asno', 'atum', 'albatroz', 'alpaca', 'arraia', 'andorinha', 'anchova', 'arminho',
                        'azulão', 'abelharuco', 'abetarda', 'abetouro', 'abibe', 'abre-asa', 'abrótea', 'arenque',
                        'açanã', 'acará', 'acará', 'acauã', 'açor', 'acurana', 'ádax', 'agulha', 'aiai', 'alcatraz',
                        'alfaiate', 'anambé', 'anhuma', 'arapaçu', 'araponga', 'ararajuba', 'aratu', 'arganaz',
                        'ariranha', 'asa-branca', 'atobá', 'baleia', 'burro', 'boi', 'borboleta', 'barata',
                        'beija-flor', 'bem-te-vi', 'boto', 'bode', 'bicho-preguiça', 'búfalo', 'besouro', 'bisonte',
                        'bicho-da-seda', 'bacalhau', 'bagre', 'baiacu', 'badejo', 'beluga', 'bufo', 'bisão', 'babuíno',
                        'barracuda', 'barbo', 'bugio', 'briba', 'bacorá', 'bodião', 'boipeva', 'boipiranga', 'bútio',
                        'bacurau', 'barbado', 'bicudo', 'bate-bico', 'batuíra', 'benedito', 'bico-de-agulha',
                        'bico-chato', 'bico-virado', 'balança-rabo', 'biguá', 'betara', 'bijupirá', 'cachorro', 'cão',
                        'cavalo', 'chimpanzé', 'canguru', 'camelo', 'coala', 'chita', 'cachalote', 'capivara', 'cutia',
                        'castor', 'crocodilo', 'cobra', 'camaleão', 'coelho', 'carneiro', 'cabra', 'cabrito', 'cágado',
                        'cascavel', 'cisne', 'coruja', 'cegonha', 'corvo', 'caranguejeira', 'caranguejo',
                        'cavalo-marinho', 'caimão', 'cobaia', 'chinchila', 'camundongo', 'cervo', 'corça', 'chacal',
                        'coiote', 'cuíca', 'coati', 'cacatua', 'condor', 'canário', 'codorna', 'camarão', 'caramujo',
                        'carrapato', 'centopeia', 'caracol', 'cigarra', 'cupim', 'caravela-portuguesa', 'coral',
                        'caxinguelê', 'cachorro-do-mato', 'cão-da-pradaria', 'cotovia', 'cagarra', 'cuco', 'curió',
                        'cardeal', 'carriça', 'caracal', 'camurça', 'calango', 'cação', 'carpa', 'cherne', 'cavala',
                        'corvina', 'candiru', 'cascudo', 'cangati', 'caranha', 'catuá', 'cigana', 'cascudo',
                        'dromedário', 'doninha', 'dourada', 'dingo', 'dinossauro', 'damão', 'dodô', 'dançador',
                        'degolado', 'diabo-da-tasmânia', 'diabo-espinhoso', 'diabo-marinho', 'dragão-de-komodo',
                        'dragão-do-banhado', 'dragão-voador', 'dragão-do-brejo', 'dragão', 'dugongo', 'diablotim',
                        'degu', 'dik-dik', 'drongo', 'dom-fafe', 'diamante-de-gould', 'diuca', 'dojô', 'elefante',
                        'égua', 'esquilo', 'enguia', 'escorpião', 'escaravelho', 'esponja', 'elefante-marinho',
                        'estrela-do-mar', 'enchova', 'ema', 'esturjão', 'espadarte', 'équidna', 'estrela-do-norte',
                        'elande', 'enho', 'emu', 'enferrujado', 'enferrujadinho', 'encontro', 'entufado', 'enxada',
                        'eremomela', 'escrevedeira', 'esmerilhão', 'esmeralda-de-cauda-azul', 'estalador', 'estorninho',
                        'estrelinha', 'euclidia', 'eilema', 'flamingo', 'formiga', 'foca', 'falcão', 'furão', 'faisão',
                        'fuinha', 'flautim', 'frango-d água', 'ferreirinho', 'figuinha', 'filipe', 'fim-fim',
                        'fogueira', 'fossa', 'fraca-cristata', 'fraca-da-guiné', 'fragata', 'franciscana', 'francolim',
                        'freira', 'freira-do-alto', 'freirinha', 'frisada', 'fruxu', 'feneco', 'facoquero', 'felosa',
                        'fulmar', 'fura-barreira', 'fura-flor', 'fura-pastos', 'furriel', 'fuselo', 'gato', 'gaivota',
                        'galo', 'galinha', 'ganso', 'gafanhoto', 'gambá', 'gavião', 'girafa', 'golfinho', 'gorila',
                        'gralha', 'girino', 'gazela', 'garça', 'geco', 'guará', 'guará', 'grilo', 'grifo', 'gnu',
                        'guaxinim', 'gamo', 'gaio', 'guepardo', 'grou', 'gritador', 'geneta', 'gerbo', 'gibão',
                        'garoupa', 'gálago', 'galhudo', 'garaju', 'garibáldi', 'garrincha', 'gaturamo', 'gauro',
                        'gavial', 'glutão', 'goete', 'golinho', 'goraz', 'gordinho', 'granadeiro', 'graúna',
                        'graveteiro', 'grazina', 'guácharo', 'guaiquica', 'guaiúba', 'guaivira', 'guanaco', 'guaracava',
                        'guaracavuçu', 'guarantã', 'guaraxaim', 'guarda-rios', 'guariba', 'guaru', 'guaxe', 'guigó',
                        'guincho', 'guinumbi', 'gurijuba', 'hipopótamo', 'hiena', 'hamster', 'harpia', 'hírax',
                        'hadoque', 'hilóquero', 'halicores', 'iguana', 'impala', 'irara', 'itapema', 'íbis', 'iaque',
                        'íbex', 'iguanara', 'indicador', 'indri', 'inhacoso', 'inhala', 'inhambu', 'inhambuapé',
                        'inhambuí', 'inhapim', 'inhauma', 'inseparável', 'ipecuacamirá', 'ipecuati', 'irapuã',
                        'iratauá', 'iratim', 'iraúna', 'irerê', 'irré', 'jacaré', 'jumento', 'jegue', 'joão-de-barro',
                        'jiboia', 'javali', 'joaninha', 'jararaca', 'jaguar', 'jabuti', 'jabiru', 'jacu', 'jaçanã',
                        'jamanta', 'jaguaré', 'joão-barbudo', 'joão-bobo', 'joão-congo', 'joão-corta-pau',
                        'joão-do-pantanal', 'joão-do- tepui', 'joão-pedreiro', 'joão-teneném', 'jacupará', 'jacamaraçu',
                        'jacamarici', 'jacamim', 'jacarerana', 'jacaretinga', 'jacuaçu', 'jacucaca', 'jacumirim',
                        'jacundá', 'jacupemba', 'jacurutu', 'jacuruxi', 'jacutinga', 'jaguacinim', 'jaguareçá',
                        'jaguarundi', 'jaguatirica', 'janauí', 'jandaia', 'jaó', 'japacanim', 'japu', 'japuaçu',
                        'jaracambeva', 'jaraqui', 'jararacuçu', 'jararaquinha', 'jaratataca', 'jaritataca', 'jataí',
                        'jatuarana', 'jaú', 'joana-guenza', 'jundiá', 'jupará', 'juriti', 'jurupensém', 'jurupoca',
                        'juruva', 'juruviara', 'krill', 'kiwi', 'kinguio', 'kakapo', 'kookaburra', 'kea', 'kowari',
                        'leão', 'leopardo', 'lobo', 'lagartixa', 'lagarto', 'lagarta', 'lacraia', 'lebre', 'lêmure',
                        'lhama', 'lince', 'lontra', 'lesma', 'libélula', 'lombriga', 'louva-a-deus', 'leão-marinho',
                        'lobo-marinho', 'lula', 'lagosta', 'lagostim', 'lampreia', 'linguado', 'lobo-do-mar',
                        'limpa-folha', 'lagarteiro', 'lóris', 'lambari', 'licranço', 'ligre', 'leopon', 'lavagante',
                        'limpa-vidro', 'lagópode', 'lenheiro', 'lemingue', 'leirão', 'lavadeira', 'laverca', 'lugre',
                        'láparo', 'límulo', 'macaco', 'mico', 'morcego', 'mosca', 'mosquito', 'minhoca', 'mula',
                        'marimbondo', 'mangangá', 'morsa', 'mariposa', 'moreia', 'marisco', 'mexilhão', 'marreco',
                        'marmota', 'marmota', 'marta', 'mocho', 'mandril', 'mamute', 'manatim', 'mono', 'muriqui',
                        'melro', 'mastodonte', 'medusa', 'merluza', 'musaranho', 'muçurana', 'maçarico', 'macuco',
                        'macuru', 'manta', 'marabu', 'mergulhão', 'mineirinho', 'mangusto', 'melharuco', 'mero',
                        'mígala', 'maguari', 'mandi', 'mandiaçu', 'mangona', 'manjuba', 'mapará', 'maracachão',
                        'maracanã', 'milhafre', 'milharós', 'mariquita', 'maritaca', 'markhor', 'marlim',
                        'martim-pescador', 'massarongo', 'matracão', 'matrinxã', 'matupiri', 'maú', 'maxalalagá',
                        'merganso', 'michole', 'miraguaia', 'mixila', 'mobelha', 'mocó', 'moleiro', 'moreiatim',
                        'muçuã', 'muçum', 'muflão', 'murucutuca', 'murucututu', 'moa', 'morcego-do-mar', 'mãe-da-lua',
                        'mãe-de-taoca', 'maitaca', 'mutum-do-nordeste', 'naja', 'narceja', 'narval', 'noitibó',
                        'negrinho', 'néon', 'namorado', 'noivinha', 'numbat', 'náutilo', 'neinei', 'nútria', 'nilgó',
                        'niquim', 'nhacundá', 'nhandiá', 'niala', 'nambu', 'nandaia', 'nandínia', 'nandu',
                        'nhambibororoca', 'onça', 'ovelha', 'orangotango', 'ornitorrinco', 'orca', 'ostra', 'osga',
                        'ouriço', 'ouriço-do-mar', 'órix', 'ocapi', 'otária', 'oscar', 'ostraceiro', 'oncinha',
                        'olho-de-boi', 'olho-de-cão', 'olho-branco', 'ógea', 'olhete', 'olho-falso', 'orictéropo',
                        'otócion', 'papagaio', 'peixe', 'pássaro', 'pato', 'pavão', 'pantera', 'preguiça', 'pônei',
                        'porco', 'porco-espinho', 'porquinho-da-índia', 'preá', 'pica-pau', 'pinguim', 'pulga',
                        'piolho', 'piranha', 'pirarucu', 'pombo', 'pinto', 'polvo', 'puma', 'paca', 'panda', 'pelicano',
                        'percevejo', 'perereca', 'periquito', 'pernilongo', 'peru', 'pardal', 'pega', 'peixe-boi',
                        'perdiz', 'pacu', 'perca', 'pescada', 'pretinho', 'pintada', 'pintarroxo', 'pintassilgo',
                        'picanço', 'pangolim', 'papa-capim', 'papa-lagarta', 'papa-moscas', 'papa-ratos', 'papa-taoca',
                        'paranaboia', 'parauacú', 'protozoário', 'quati', 'quatipuru', 'quatimirim', 'quatipuruzinho',
                        'queixada', 'quelea', 'quimera', 'quetzal', 'quero-quero', 'quem-quem', 'quiriquiri',
                        'quebra-nozes', 'quoll', 'quirquincho', 'quelônios', 'quebra-ossos',
                        'quebra-sementes-do-niassa', 'quem-te-vestiu', 'rato', 'ratazana', 'raposa', 'rinoceronte',
                        'rã', 'rouxinol', 'rena', 'raia', 'rola', 'rolinha', 'rela', 'robalo', 'rabudo',
                        'ratão-do-banhado', 'raposa-voadora', 'roaz-corvineiro', 'raposão', 'rendeira', 'rolieiro',
                        'risadinha', 'rendadinho', 'rapazinho', 'rombudo', 'rabudinho', 'rei-do-bosque', 'rêmora',
                        'remeiro', 'rodóstomo', 'realito', 'rabo-amarelo', 'rabo-branco', 'rabirruivo', 'rabicurta',
                        'rabo-de-palha', 'rabo-de-junco', 'rabo-de-arame', 'rabo-de-escrivão', 'rabo-de-espinho',
                        'rabo-espinhoso', 'rabo-mole-da-serra', 'sabiá', 'sapo', 'sagui', 'saúva', 'sardinha', 'siri',
                        'sucuri', 'serpente', 'suricate', 'surucucu', 'surucucurana', 'salmão', 'solha', 'sanguessuga',
                        'salamandra', 'seriema', 'saci', 'saguiru', 'saí', 'saicanga', 'saíra', 'salamanta', 'salema',
                        'salteira', 'sanã', 'sanhaço', 'sapateira', 'saracura', 'saracuraçu', 'sarapó', 'sarda',
                        'sardão', 'sargento', 'saripoca', 'saruê', 'saudade', 'saurá', 'savacu', 'savelha', 'sebinho',
                        'secretário', 'seixoeira', 'serelepe', 'sertanejo escuro', 'serval', 'sete cores da amazônia',
                        'singanga', 'siripipi de benguela', 'sisão', 'sororoca', 'socó', 'socoí', 'sovela vermelha',
                        'sovi', 'suaçubóia', 'suçuarana', 'suiriri', 'surubi', 'surucuá', 'sacarrabos', 'solenodonte',
                        'tigre', 'tubarão', 'tartaruga', 'touro', 'tatu', 'tamanduá', 'tucano', 'tarântula', 'toupeira',
                        'texugo', 'tapir', 'tainha', 'truta', 'tamboril', 'tecelão', 'tentilhão', 'tico-tico', 'tordo',
                        'tritão', 'traça', 'tatuí', 'tucuxi', 'tuco-tuco', 'toninha', 'teiú', 'tuiuiú', 'társio',
                        'tamanduaí', 'tapiti', 'tenreque', 'tropiduro', 'truirapeva', 'tupaia', 'tracajá',
                        'tagarela-europeu', 'tangará', 'tapicuru', 'tarambola', 'teque-teque', 'tilápia', 'timboré',
                        'tordeia', 'tororó', 'toutinegra', 'traíra', 'trairão', 'trepador', 'trombeteiro', 'turu-turu',
                        'tucunaré', 'tuim', 'urso', 'urso panda', 'urubu', 'unicórnio', 'uacari', 'uaru', 'ubarana',
                        'udu', 'uritutu', 'uí-pi', 'uiraçu', 'uirapuru', 'unau', 'unha-longa', 'uru', 'urubuzinho',
                        'urumutum', 'urupiagara', 'urutaí', 'urutau', 'urutaurana', 'urutu', 'vaca', 'vespa',
                        'vaga-lume', 'veado', 'víbora', 'viúva-negra', 'viúva', 'vieira', 'vison', 'vira-bosta',
                        'vitela', 'vaca-marinha', 'verdilhão', 'verdinho', 'vicunha', 'vira-folha', 'vira-pedras',
                        'viruçu', 'vissiá', 'vite-vite', 'vi-vió', 'viscacha', 'vespertilio', 'vermelho-henrique',
                        'veste-amarela', 'vigonho', 'vomba', 'vombate', 'wallaby', 'wombat', 'xexéu', 'xaréu',
                        'xarelete', 'xuê', 'xuê-açu', 'xangó', 'xajá', 'xaru', 'xauim', 'xero', 'ximango', 'xofrango',
                        'ximburé', 'xira', 'xuri', 'xixarro', 'xantídeo', 'xumberga', 'xará', 'ynambu', 'yak', 'zebra',
                        'zebu', 'zangão', 'zorrilho', 'zaglosso', 'zabelê', 'zidedê', 'zaragateiro', 'zombeteiro',
                        'zarro']

    # def __init__(self):
    #     self._animals = [animal.lower() for animal in self._animals if ' ' not in animal]
    #     print(self._animals)


class Adjective(Generator):
    """
    Database for adjectives.
    """

    # _list: list[str] = ['abandoned', 'able', 'absolute', 'adorable', 'adventurous', 'academic', 'acceptable',
    #                     'acclaimed', 'accomplished', 'accurate', 'aching', 'acidic', 'acrobatic', 'active',
    #                     'actual', 'adept', 'admirable', 'admired', 'adolescent', 'adorable', 'adored', 'advanced',
    #                     'afraid', 'affectionate', 'aged', 'aggravating', 'aggressive', 'agile', 'agitated',
    #                     'agonizing', 'agreeable', 'ajar', 'alarmed', 'alarming', 'alert', 'alienated', 'alive',
    #                     'all', 'altruistic', 'amazing', 'ambitious', 'ample', 'amused', 'amusing', 'anchored',
    #                     'ancient', 'angelic', 'angry', 'anguished', 'animated', 'annual', 'another', 'antique',
    #                     'anxious', 'any', 'apprehensive', 'appropriate', 'apt', 'arctic', 'arid', 'aromatic',
    #                     'artistic', 'ashamed', 'assured', 'astonishing', 'athletic', 'attached', 'attentive',
    #                     'attractive', 'austere', 'authentic', 'authorized', 'automatic', 'avaricious', 'average',
    #                     'aware', 'awesome', 'awful', 'awkward', 'babyish', 'bad', 'back', 'baggy', 'bare',
    #                     'barren', 'basic', 'beautiful', 'belated', 'beloved', 'beneficial', 'better', 'best',
    #                     'bewitched', 'big', 'big-hearted', 'biodegradable', 'bite-sized', 'bitter', 'black',
    #                     'black-and-white', 'bland', 'blank', 'blaring', 'bleak', 'blind', 'blissful', 'blond',
    #                     'blue', 'blushing', 'bogus', 'boiling', 'bold', 'bony', 'boring', 'bossy', 'both',
    #                     'bouncy', 'bountiful', 'bowed', 'brave', 'breakable', 'brief', 'bright', 'brilliant',
    #                     'brisk', 'broken', 'bronze', 'brown', 'bruised', 'bubbly', 'bulky', 'bumpy', 'buoyant',
    #                     'burdensome', 'burly', 'bustling', 'busy', 'buttery', 'buzzing', 'calculating', 'calm',
    #                     'candid', 'canine', 'capital', 'carefree', 'careful', 'careless', 'caring', 'cautious',
    #                     'cavernous', 'celebrated', 'charming', 'cheap', 'cheerful', 'cheery', 'chief', 'chilly',
    #                     'chubby', 'circular', 'classic', 'clean', 'clear', 'clear-cut', 'clever', 'close',
    #                     'closed', 'cloudy', 'clueless', 'clumsy', 'cluttered', 'coarse', 'cold', 'colorful',
    #                     'colorless', 'colossal', 'comfortable', 'common', 'compassionate', 'competent',
    #                     'complete', 'complex', 'complicated', 'composed', 'concerned', 'concrete', 'confused',
    #                     'conscious', 'considerate', 'constant', 'content', 'conventional', 'cooked', 'cool',
    #                     'cooperative', 'coordinated', 'corny', 'corrupt', 'costly', 'courageous', 'courteous',
    #                     'crafty', 'crazy', 'creamy', 'creative', 'creepy', 'criminal', 'crisp', 'critical',
    #                     'crooked', 'crowded', 'cruel', 'crushing', 'cuddly', 'cultivated', 'cultured',
    #                     'cumbersome', 'curly', 'curvy', 'cute', 'cylindrical', 'damaged', 'damp', 'dangerous',
    #                     'dapper', 'daring', 'darling', 'dark', 'dazzling', 'dead', 'deadly', 'deafening', 'dear',
    #                     'dearest', 'decent', 'decimal', 'decisive', 'deep', 'defenseless', 'defensive', 'defiant',
    #                     'deficient', 'definite', 'definitive', 'delayed', 'delectable', 'delicious', 'delightful',
    #                     'delirious', 'demanding', 'dense', 'dental', 'dependable', 'dependent', 'descriptive',
    #                     'deserted', 'detailed', 'determined', 'devoted', 'different', 'difficult', 'digital',
    #                     'diligent', 'dim', 'dimpled', 'dimwitted', 'direct', 'disastrous', 'discrete',
    #                     'disfigured', 'disgusting', 'disloyal', 'dismal', 'distant', 'downright', 'dreary',
    #                     'dirty', 'disguised', 'dishonest', 'dismal', 'distant', 'distinct', 'distorted', 'dizzy',
    #                     'dopey', 'doting', 'double', 'downright', 'drab', 'drafty', 'dramatic', 'dreary',
    #                     'droopy', 'dry', 'dual', 'dull', 'dutiful', 'each', 'eager', 'earnest', 'early', 'easy',
    #                     'easy-going', 'ecstatic', 'edible', 'educated', 'elaborate', 'elastic', 'elated',
    #                     'elderly', 'electric', 'elegant', 'elementary', 'elliptical', 'embarrassed',
    #                     'embellished', 'eminent', 'emotional', 'empty', 'enchanted', 'enchanting', 'energetic',
    #                     'enlightened', 'enormous', 'enraged', 'entire', 'envious', 'equal', 'equatorial',
    #                     'essential', 'esteemed', 'ethical', 'euphoric', 'even', 'evergreen', 'everlasting',
    #                     'every', 'evil', 'exalted', 'excellent', 'exemplary', 'exhausted', 'excitable', 'excited',
    #                     'exciting', 'exotic', 'expensive', 'experienced', 'expert', 'extraneous', 'extroverted',
    #                     'extra-large', 'extra-small', 'fabulous', 'failing', 'faint', 'fair', 'faithful', 'fake',
    #                     'false', 'familiar', 'famous', 'fancy', 'fantastic', 'far', 'faraway', 'far-flung',
    #                     'far-off', 'fast', 'fat', 'fatal', 'fatherly', 'favorable', 'favorite', 'fearful',
    #                     'fearless', 'feisty', 'feline', 'female', 'feminine', 'few', 'fickle', 'filthy', 'fine',
    #                     'finished', 'firm', 'first', 'firsthand', 'fitting', 'fixed', 'flaky', 'flamboyant',
    #                     'flashy', 'flat', 'flawed', 'flawless', 'flickering', 'flimsy', 'flippant', 'flowery',
    #                     'fluffy', 'fluid', 'flustered', 'focused', 'fond', 'foolhardy', 'foolish', 'forceful',
    #                     'forked', 'formal', 'forsaken', 'forthright', 'fortunate', 'fragrant', 'frail', 'frank',
    #                     'frayed', 'free', 'french', 'fresh', 'frequent', 'friendly', 'frightened', 'frightening',
    #                     'frigid', 'frilly', 'frizzy', 'frivolous', 'front', 'frosty', 'frozen', 'frugal',
    #                     'fruitful', 'full', 'fumbling', 'functional', 'funny', 'fussy', 'fuzzy', 'gargantuan',
    #                     'gaseous', 'general', 'generous', 'gentle', 'genuine', 'giant', 'giddy', 'gigantic',
    #                     'gifted', 'giving', 'glamorous', 'glaring', 'glass', 'gleaming', 'gleeful', 'glistening',
    #                     'glittering', 'gloomy', 'glorious', 'glossy', 'glum', 'golden', 'good', 'good-natured',
    #                     'gorgeous', 'graceful', 'gracious', 'grand', 'grandiose', 'granular', 'grateful', 'grave',
    #                     'gray', 'great', 'greedy', 'green', 'gregarious', 'grim', 'grimy', 'gripping', 'grizzled',
    #                     'gross', 'grotesque', 'grouchy', 'grounded', 'growing', 'growling', 'grown', 'grubby',
    #                     'gruesome', 'grumpy', 'guilty', 'gullible', 'gummy', 'hairy', 'half', 'handmade',
    #                     'handsome', 'handy', 'happy', 'happy-go-lucky', 'hard', 'hard-to-find', 'harmful',
    #                     'harmless', 'harmonious', 'harsh', 'hasty', 'hateful', 'haunting', 'healthy', 'heartfelt',
    #                     'hearty', 'heavenly', 'heavy', 'hefty', 'helpful', 'helpless', 'hidden', 'hideous',
    #                     'high', 'high-level', 'hilarious', 'hoarse', 'hollow', 'homely', 'honest', 'honorable',
    #                     'honored', 'hopeful', 'horrible', 'hospitable', 'hot', 'huge', 'humble', 'humiliating',
    #                     'humming', 'humongous', 'hungry', 'hurtful', 'husky', 'icky', 'icy', 'ideal',
    #                     'idealistic', 'identical', 'idle', 'idiotic', 'idolized', 'ignorant', 'ill', 'illegal',
    #                     'ill-fated', 'ill-informed', 'illiterate', 'illustrious', 'imaginary', 'imaginative',
    #                     'immaculate', 'immaterial', 'immediate', 'immense', 'impassioned', 'impeccable',
    #                     'impartial', 'imperfect', 'imperturbable', 'impish', 'impolite', 'important',
    #                     'impossible', 'impractical', 'impressionable', 'impressive', 'improbable', 'impure',
    #                     'inborn', 'incomparable', 'incompatible', 'incomplete', 'inconsequential', 'incredible',
    #                     'indelible', 'inexperienced', 'indolent', 'infamous', 'infantile', 'infatuated',
    #                     'inferior', 'infinite', 'informal', 'innocent', 'insecure', 'insidious', 'insignificant',
    #                     'insistent', 'instructive', 'insubstantial', 'intelligent', 'intent', 'intentional',
    #                     'interesting', 'internal', 'international', 'intrepid', 'ironclad', 'irresponsible',
    #                     'irritating', 'itchy', 'jaded', 'jagged', 'jam-packed', 'jaunty', 'jealous', 'jittery',
    #                     'joint', 'jolly', 'jovial', 'joyful', 'joyous', 'jubilant', 'judicious', 'juicy', 'jumbo',
    #                     'junior', 'jumpy', 'juvenile', 'kaleidoscopic', 'keen', 'key', 'kind', 'kindhearted',
    #                     'kindly', 'klutzy', 'knobby', 'knotty', 'knowledgeable', 'knowing', 'known', 'kooky',
    #                     'kosher', 'lame', 'lanky', 'large', 'last', 'lasting', 'late', 'lavish', 'lawful', 'lazy',
    #                     'leading', 'lean', 'leafy', 'left', 'legal', 'legitimate', 'light', 'lighthearted',
    #                     'likable', 'likely', 'limited', 'limp', 'limping', 'linear', 'lined', 'liquid', 'little',
    #                     'live', 'lively', 'livid', 'loathsome', 'lone', 'lonely', 'long', 'long-term', 'loose',
    #                     'lopsided', 'lost', 'loud', 'lovable', 'lovely', 'loving', 'low', 'loyal', 'lucky',
    #                     'lumbering', 'luminous', 'lumpy', 'lustrous', 'luxurious', 'mad', 'made-up',
    #                     'magnificent', 'majestic', 'major', 'male', 'mammoth', 'married', 'marvelous',
    #                     'masculine', 'massive', 'mature', 'meager', 'mealy', 'mean', 'measly', 'meaty', 'medical',
    #                     'mediocre', 'medium', 'meek', 'mellow', 'melodic', 'memorable', 'menacing', 'merry',
    #                     'messy', 'metallic', 'mild', 'milky', 'mindless', 'miniature', 'minor', 'minty',
    #                     'miserable', 'miserly', 'misguided', 'misty', 'mixed', 'modern', 'modest', 'moist',
    #                     'monstrous', 'monthly', 'monumental', 'moral', 'mortified', 'motherly', 'motionless',
    #                     'mountainous', 'muddy', 'muffled', 'multicolored', 'mundane', 'murky', 'mushy', 'musty',
    #                     'muted', 'mysterious', 'naive', 'narrow', 'nasty', 'natural', 'naughty', 'nautical',
    #                     'near', 'neat', 'necessary', 'needy', 'negative', 'neglected', 'negligible',
    #                     'neighboring', 'nervous', 'new', 'next', 'nice', 'nifty', 'nimble', 'nippy', 'nocturnal',
    #                     'noisy', 'nonstop', 'normal', 'notable', 'noted', 'noteworthy', 'novel', 'noxious',
    #                     'numb', 'nutritious', 'nutty', 'obedient', 'obese', 'oblong', 'oily', 'oblong', 'obvious',
    #                     'occasional', 'odd', 'oddball', 'offbeat', 'offensive', 'official', 'old',
    #                     'old-fashioned', 'only', 'open', 'optimal', 'optimistic', 'opulent', 'orange', 'orderly',
    #                     'organic', 'ornate', 'ornery', 'ordinary', 'original', 'other', 'our', 'outlying',
    #                     'outgoing', 'outlandish', 'outrageous', 'outstanding', 'oval', 'overcooked', 'overdue',
    #                     'overjoyed', 'overlooked', 'palatable', 'pale', 'paltry', 'parallel', 'parched',
    #                     'partial', 'passionate', 'past', 'pastel', 'peaceful', 'peppery', 'perfect', 'perfumed',
    #                     'periodic', 'perky', 'personal', 'pertinent', 'pesky', 'pessimistic', 'petty', 'phony',
    #                     'physical', 'piercing', 'pink', 'pitiful', 'plain', 'plaintive', 'plastic', 'playful',
    #                     'pleasant', 'pleased', 'pleasing', 'plump', 'plush', 'polished', 'polite', 'political',
    #                     'pointed', 'pointless', 'poised', 'poor', 'popular', 'portly', 'posh', 'positive',
    #                     'possible', 'potable', 'powerful', 'powerless', 'practical', 'precious', 'present',
    #                     'prestigious', 'pretty', 'precious', 'previous', 'pricey', 'prickly', 'primary', 'prime',
    #                     'pristine', 'private', 'prize', 'probable', 'productive', 'profitable', 'profuse',
    #                     'proper', 'proud', 'prudent', 'punctual', 'pungent', 'puny', 'pure', 'purple', 'pushy',
    #                     'putrid', 'puzzled', 'puzzling', 'quaint', 'qualified', 'quarrelsome', 'quarterly',
    #                     'queasy', 'querulous', 'questionable', 'quick', 'quick-witted', 'quiet', 'quintessential',
    #                     'quirky', 'quixotic', 'quizzical', 'radiant', 'ragged', 'rapid', 'rare', 'rash', 'raw',
    #                     'recent', 'reckless', 'rectangular', 'ready', 'real', 'realistic', 'reasonable', 'red',
    #                     'reflecting', 'regal', 'regular', 'reliable', 'relieved', 'remarkable', 'remorseful',
    #                     'remote', 'repentant', 'required', 'respectful', 'responsible', 'repulsive', 'revolving',
    #                     'rewarding', 'rich', 'rigid', 'right', 'ringed', 'ripe', 'roasted', 'robust', 'rosy',
    #                     'rotating', 'rotten', 'rough', 'round', 'rowdy', 'royal', 'rubbery', 'rundown', 'ruddy',
    #                     'rude', 'runny', 'rural', 'rusty', 'sad', 'safe', 'salty', 'same', 'sandy', 'sane',
    #                     'sarcastic', 'sardonic', 'satisfied', 'scaly', 'scarce', 'scared', 'scary', 'scented',
    #                     'scholarly', 'scientific', 'scornful', 'scratchy', 'scrawny', 'second', 'secondary',
    #                     'second-hand', 'secret', 'self-assured', 'self-reliant', 'selfish', 'sentimental',
    #                     'separate', 'serene', 'serious', 'serpentine', 'several', 'severe', 'shabby', 'shadowy',
    #                     'shady', 'shallow', 'shameful', 'shameless', 'sharp', 'shimmering', 'shiny', 'shocked',
    #                     'shocking', 'shoddy', 'short', 'short-term', 'showy', 'shrill', 'shy', 'sick', 'silent',
    #                     'silky', 'silly', 'silver', 'similar', 'simple', 'simplistic', 'sinful', 'single',
    #                     'sizzling', 'skeletal', 'skinny', 'sleepy', 'slight', 'slim', 'slimy', 'slippery', 'slow',
    #                     'slushy', 'small', 'smart', 'smoggy', 'smooth', 'smug', 'snappy', 'snarling', 'sneaky',
    #                     'sniveling', 'snoopy', 'sociable', 'soft', 'soggy', 'solid', 'somber', 'some',
    #                     'spherical', 'sophisticated', 'sore', 'sorrowful', 'soulful', 'soupy', 'sour', 'spanish',
    #                     'sparkling', 'sparse', 'specific', 'spectacular', 'speedy', 'spicy', 'spiffy', 'spirited',
    #                     'spiteful', 'splendid', 'spotless', 'spotted', 'spry', 'square', 'squeaky', 'squiggly',
    #                     'stable', 'staid', 'stained', 'stale', 'standard', 'starchy', 'stark', 'starry', 'steep',
    #                     'sticky', 'stiff', 'stimulating', 'stingy', 'stormy', 'straight', 'strange', 'steel',
    #                     'strict', 'strident', 'striking', 'striped', 'strong', 'studious', 'stunning',
    #                     'stupendous', 'stupid', 'sturdy', 'stylish', 'subdued', 'submissive', 'substantial',
    #                     'subtle', 'suburban', 'sudden', 'sugary', 'sunny', 'super', 'superb', 'superficial',
    #                     'superior', 'supportive', 'sure-footed', 'surprised', 'suspicious', 'svelte', 'sweaty',
    #                     'sweet', 'sweltering', 'swift', 'sympathetic', 'tall', 'talkative', 'tame', 'tan',
    #                     'tangible', 'tart', 'tasty', 'tattered', 'taut', 'tedious', 'teeming', 'tempting',
    #                     'tender', 'tense', 'tepid', 'terrible', 'terrific', 'testy', 'thankful', 'that', 'these',
    #                     'thick', 'thin', 'third', 'thirsty', 'this', 'thorough', 'thorny', 'those', 'thoughtful',
    #                     'threadbare', 'thrifty', 'thunderous', 'tidy', 'tight', 'timely', 'tinted', 'tiny',
    #                     'tired', 'torn', 'total', 'tough', 'traumatic', 'treasured', 'tremendous', 'tragic',
    #                     'trained', 'tremendous', 'triangular', 'tricky', 'trifling', 'trim', 'trivial',
    #                     'troubled', 'true', 'trusting', 'trustworthy', 'trusty', 'truthful', 'tubby', 'turbulent',
    #                     'twin', 'ugly', 'ultimate', 'unacceptable', 'unaware', 'uncomfortable', 'uncommon',
    #                     'unconscious', 'understated', 'unequaled', 'uneven', 'unfinished', 'unfit', 'unfolded',
    #                     'unfortunate', 'unhappy', 'unhealthy', 'uniform', 'unimportant', 'unique', 'united',
    #                     'unkempt', 'unknown', 'unlawful', 'unlined', 'unlucky', 'unnatural', 'unpleasant',
    #                     'unrealistic', 'unripe', 'unruly', 'unselfish', 'unsightly', 'unsteady', 'unsung',
    #                     'untidy', 'untimely', 'untried', 'untrue', 'unused', 'unusual', 'unwelcome', 'unwieldy',
    #                     'unwilling', 'unwitting', 'unwritten', 'upbeat', 'upright', 'upset', 'urban', 'usable',
    #                     'used', 'useful', 'useless', 'utilized', 'utter', 'vacant', 'vague', 'vain', 'valid',
    #                     'valuable', 'vapid', 'variable', 'vast', 'velvety', 'venerated', 'vengeful', 'verifiable',
    #                     'vibrant', 'vicious', 'victorious', 'vigilant', 'vigorous', 'villainous', 'violet',
    #                     'violent', 'virtual', 'virtuous', 'visible', 'vital', 'vivacious', 'vivid', 'voluminous',
    #                     'wan', 'warlike', 'warm', 'warmhearted', 'warped', 'wary', 'wasteful', 'watchful',
    #                     'waterlogged', 'watery', 'wavy', 'wealthy', 'weak', 'weary', 'webbed', 'wee', 'weekly',
    #                     'weepy', 'weighty', 'weird', 'welcome', 'well-documented', 'well-groomed',
    #                     'well-informed', 'well-lit', 'well-made', 'well-off', 'well-to-do', 'well-worn', 'wet',
    #                     'which', 'whimsical', 'whirlwind', 'whispered', 'white', 'whole', 'whopping', 'wicked',
    #                     'wide', 'wide-eyed', 'wiggly', 'wild', 'willing', 'wilted', 'winding', 'windy', 'winged',
    #                     'wiry', 'wise', 'witty', 'wobbly', 'woeful', 'wonderful', 'wooden', 'woozy', 'wordy',
    #                     'worldly', 'worn', 'worried', 'worrisome', 'worse', 'worst', 'worthless', 'worthwhile',
    #                     'worthy', 'wrathful', 'wretched', 'writhing', 'wrong', 'wry', 'yawning', 'yearly',
    #                     'yellow', 'yellowish', 'young', 'youthful', 'yummy', 'zany', 'zealous', 'zesty', 'zigzag']

    _list: list[str] = ['acessível', 'acolhedor', 'adorável', 'admirável', 'ágil', 'agradável', 'agressivo', 'alegre',
                        'altruísta', 'amado', 'amargurado', 'ambicioso', 'amigável', 'amoroso', 'animado', 'ansioso',
                        'antipático', 'aplicado', 'apressado', 'arrogante', 'assertivo', 'atencioso', 'atraente',
                        'atrevido', 'autêntico', 'autoritário', 'avarento', 'aventureiro', 'batalhador', 'belo',
                        'bem-comportado', 'bem-educado', 'bem-humorado', 'bem-intencionado', 'birrento',
                        'bisbilhoteiro', 'bom', 'bombástico', 'bondoso', 'bonito', 'bravo', 'brilhante', 'brincalhão',
                        'bruto', 'calmo', 'capacitado', 'carente', 'caridoso', 'carinhoso', 'carismático', 'cativante',
                        'charmoso', 'chato', 'cheiroso', 'chique', 'cínico', 'ciumento', 'civilizado', 'coerente',
                        'companheiro', 'competente', 'competitivo', 'comportado', 'compreensivo', 'compulsivo',
                        'comunicativo', 'confiante', 'corajoso', 'cordial', 'covarde', 'criativo', 'criterioso',
                        'crítico', 'cruel', 'cuidadoso', 'culto', 'curioso', 'debochado', 'decente', 'dedicado',
                        'delicado', 'dengoso', 'dependente', 'depressivo', 'desafiador', 'desapegado', 'desconfiado',
                        'descontraído', 'desejado', 'desenvolto', 'desequilibrado', 'desesperado', 'desleal',
                        'desleixado', 'deslumbrante', 'desmotivado', 'desobediente', 'desonesto', 'determinado',
                        'devagar', 'digno', 'disciplinado', 'disponível', 'dissimulado', 'distraído', 'divertido',
                        'doce', 'duvidoso', 'educado', 'eficiente', 'egoísta', 'elegante', 'empenhado', 'empolgado',
                        'encantador', 'engraçado', 'entendido', 'entusiasmado', 'equilibrado', 'esbelto', 'esclarecido',
                        'esforçado', 'espantoso', 'especial', 'esperançoso', 'esperto', 'espetacular', 'espirituoso',
                        'espontâneo', 'estourado', 'estressado', 'estudioso', 'estúpido', 'eufórico', 'excelente',
                        'exigente', 'experiente', 'explosivo', 'extraordinário', 'extrovertido', 'fabuloso', 'faceiro',
                        'falso', 'fanático', 'fantástico', 'fascinante', 'feio', 'feliz', 'fenomenal', 'feroz',
                        'fervoroso', 'fiel', 'fingido', 'firme', 'fofo', 'formidável', 'formoso', 'forte', 'fracassado',
                        'fraco', 'franco', 'frio', 'frustrado', 'fútil', 'gaiteiro', 'galanteador', 'ganancioso',
                        'generoso', 'genial', 'gentil', 'genuíno', 'gigante', 'glorioso', 'gordo', 'gostoso',
                        'gracioso', 'grande', 'grato', 'grosseiro', 'grosso', 'guloso', 'habilidoso', 'harmonioso',
                        'heroico', 'hilário', 'hilariante', 'hipócrita', 'histérico', 'honesto', 'honorável', 'honrado',
                        'horrível', 'horroroso', 'hostil', 'hospitaleiro', 'humanitário', 'humilde', 'ideal',
                        'ignorante', 'igual', 'iluminado', 'ilustre', 'imbatível', 'imortal', 'imparcial', 'imperfeito',
                        'impulsivo', 'incoerente', 'incompetente', 'incrível', 'indeciso', 'independente', 'infiel',
                        'ingênuo', 'ingrato', 'injusto', 'inocente', 'inovador', 'inquieto', 'inseguro', 'insensato',
                        'insuportável', 'íntegro', 'inteligente', 'intenso', 'interessante', 'intrometido', 'invejoso',
                        'irresponsável', 'irritado', 'jeitoso', 'jocoso', 'jovem', 'jovial', 'jubiloso', 'justiceiro',
                        'justo', 'largo', 'leal', 'ledo', 'legal', 'legítimo', 'letrado', 'leve', 'lícito', 'líder',
                        'livre', 'lindo', 'louco', 'louvável', 'lúcido', 'lutador', 'luxuoso', 'maduro', 'mágico',
                        'magnífico', 'magoado', 'maior', 'majestoso', 'malandro', 'maldoso', 'malicioso', 'malvado',
                        'mandão', 'manhoso', 'maravilhoso', 'marcante', 'máximo', 'medroso', 'meigo', 'melancólico',
                        'melhor', 'mentiroso', 'mesquinho', 'mimado', 'minucioso', 'misterioso', 'moderado', 'moderno',
                        'modesto', 'mortal', 'motivado', 'natural', 'narcisista', 'necessário', 'necessitado',
                        'negativista', 'negligente', 'nervoso', 'neurótico', 'nobre', 'nojento', 'normal', 'nostálgico',
                        'notável', 'novo', 'obcecado', 'obediente', 'objetivo', 'observador', 'obstinado', 'odioso',
                        'oportunista', 'otário', 'ordeiro', 'ordinário', 'organizado', 'orgulhoso', 'original',
                        'otimista', 'ótimo', 'ousado', 'pacato', 'paciente', 'passivo', 'pequeno', 'perfeccionista',
                        'perfeito', 'perseverante', 'persistente', 'perspicaz', 'pessimista', 'piedoso', 'pioneiro',
                        'poderoso', 'ponderado', 'pontual', 'possessivo', 'potente', 'prazeroso', 'precipitado',
                        'preconceituoso', 'preguiçoso', 'prepotente', 'preocupado', 'preparado', 'presunçoso',
                        'prestativo', 'prevenido', 'primoroso', 'problemático', 'produtivo', 'próspero', 'protetor',
                        'prudente', 'puro', 'qualificado', 'quente', 'querençoso', 'querido', 'quistoso', 'rabugento',
                        'racional', 'radiante', 'raivosa', 'rancoroso', 'rápido', 'razoável', 'realista', 'realizado',
                        'rebelde', 'receptivo', 'refinado', 'rejeitado', 'relapso', 'relaxado', 'reluzente', 'renomado',
                        'reservado', 'resiliente', 'resistente', 'respeitado', 'respeitável', 'responsável',
                        'revoltado', 'rígido', 'rigoroso', 'risonho', 'robusto', 'romântico', 'rude', 'sábio', 'sadio',
                        'sagaz', 'sapeca', 'sarcástico', 'satisfeito', 'saudável', 'sedentário', 'sedutor', 'seguro',
                        'sensacional', 'sensato', 'sensível', 'sentimental', 'serelepe', 'sereno', 'sério', 'simpático',
                        'sincero', 'singular', 'sociável', 'sofisticado', 'sofrido', 'solícito', 'solidário',
                        'sonhador', 'sorridente', 'sossegado', 'suave', 'sublime', 'sufocado', 'sutil', 'tagarela',
                        'talentoso', 'tedioso', 'teimoso', 'temente', 'tendencioso', 'tentador', 'terno', 'tímido',
                        'tirano', 'tocante', 'tolerante', 'trabalhador', 'traiçoeiro', 'traidor', 'transigente',
                        'trapaceiro', 'tranquilo', 'transparente', 'tristonho', 'triunfal', 'ultrapassado', 'único',
                        'unificador', 'urbano', 'útil', 'vaidoso', 'valente', 'valioso', 'valoroso', 'veloz',
                        'vencedor', 'venerável', 'verdadeiro', 'vergonhoso', 'verídico', 'versátil', 'vibrante',
                        'vigarista', 'vingativo', 'vigilante', 'vigoroso', 'viril', 'virtuoso', 'visionário', 'vital',
                        'vitorioso', 'vívido', 'voraz', 'vulgar', 'vulnerável', 'windsurfista', 'xabouqueiro',
                        'xardoso', 'xodó', 'zangado', 'zelador', 'zeloso', 'zen', 'zoado']

    # def __init__(self):
    #     self._adjectives = [adjective.lower() for adjective in self._adjectives if ' ' not in adjective]
    #     print(self._adjectives)


class Name(Generator):
    """
    Database for names.
    """

    # _list: list[(str, Gender)] = []

    _list = ['maria', 'jose', 'ana', 'joao', 'antonio', 'francisco', 'carlos', 'paulo', 'pedro', 'lucas', 'luiz',
             'marcos', 'luis', 'gabriel', 'rafael', 'francisca', 'daniel', 'marcelo', 'bruno', 'eduardo', 'felipe',
             'raimundo', 'rodrigo', 'antonia', 'manoel', 'mateus', 'andre', 'adriana', 'juliana', 'fernando', 'marcia',
             'fabio', 'leonardo', 'gustavo', 'fernanda', 'patricia', 'guilherme', 'aline', 'leandro', 'tiago', 'sandra',
             'anderson', 'camila', 'ricardo', 'marcio', 'amanda', 'jorge', 'bruna', 'sebastiao', 'jessica', 'alexandre',
             'roberto', 'leticia', 'julia', 'edson', 'luciana', 'diego', 'vitor', 'vanessa', 'sergio', 'mariana',
             'gabriela', 'vera', 'vitoria', 'larissa', 'claudia', 'beatriz', 'luana', 'rita', 'sonia', 'claudio',
             'matheus', 'renata', 'thiago', 'eliane', 'josefa', 'simone', 'geraldo', 'adriano', 'luciano', 'julio',
             'natalia', 'renato', 'cristiane', 'carla', 'debora', 'alex', 'rosangela', 'jaqueline', 'rosa', 'vinicius',
             'daniela', 'aparecida', 'marlene', 'terezinha', 'raimunda', 'rogerio', 'samuel', 'andreia', 'fabiana',
             'lucia', 'raquel', 'angela', 'rafaela', 'ronaldo', 'joana', 'mario', 'flavio', 'igor', 'douglas', 'luzia',
             'elaine', 'davi', 'jeferson', 'manuel', 'daniele', 'regina', 'cicero', 'daiane', 'sueli', 'alessandra',
             'victor', 'miguel', 'isabel', 'robson', 'mauricio', 'sara', 'flavia', 'bianca', 'danilo', 'erica',
             'viviane', 'henrique', 'caio', 'reginaldo', 'silvana', 'priscila', 'paula', 'luiza', 'tereza', 'isabela',
             'marta', 'joaquim', 'benedito', 'caroline', 'gilberto', 'janaina', 'laura', 'marli', 'tatiane', 'marina',
             'marco', 'alan', 'silvia', 'monica', 'tais', 'michele', 'nelson', 'solange', 'edna', 'fatima', 'helena',
             'cristiano', 'cristina', 'alice', 'carolina', 'rosana', 'elias', 'wilson', 'valdir', 'andressa', 'celia',
             'valeria', 'eliana', 'sabrina', 'emerson', 'luan', 'andrea', 'david', 'tania', 'renan', 'barbara',
             'severino', 'thais', 'denise', 'roseli', 'fabricio', 'mauro', 'gisele', 'jonas', 'marilene', 'katia',
             'eva', 'gilmar', 'jean', 'fabiano', 'milena', 'wesley', 'diogo', 'adilson', 'jair', 'eduarda',
             'alessandro', 'everton', 'osvaldo', 'elisangela', 'vilma', 'geovana', 'willian', 'gilson', 'luciene',
             'joel', 'tamires', 'roberta', 'tatiana', 'elza', 'talita', 'silvio', 'marcela', 'pamela', 'helio', 'irene',
             'vania', 'josiane', 'livia', 'maicon', 'reinaldo', 'pablo', 'artur', 'vagner', 'ivone', 'cintia', 'valter',
             'lais', 'ivan', 'celso', 'taina', 'cleiton', 'benedita', 'sebastiana', 'joice', 'vanderlei', 'arthur',
             'mirian', 'vicente', 'milton', 'domingos', 'sandro', 'wagner', 'moises', 'gabriele', 'edilson',
             'elizabete', 'ademir', 'angelica', 'adao', 'brenda', 'evandro', 'veronica', 'cesar', 'karina', 'rosilene',
             'nair', 'valmir', 'murilo', 'juliano', 'neusa', 'margarida', 'neuza', 'edvaldo', 'neide', 'ailton',
             'raissa', 'junior', 'maiara', 'breno', 'nicolas', 'franciele', 'lorena', 'samara', 'ruan', 'lilian',
             'janete', 'cicera', 'alberto', 'giovana', 'severina', 'cleide', 'lara', 'nicole', 'rubens', 'augusto',
             'nilton', 'cecilia', 'yasmin', 'conceicao', 'cleber', 'osmar', 'ingrid', 'selma', 'leila', 'raiane',
             'nilson', 'orlando', 'hugo', 'otavio', 'ester', 'vinicios', 'regiane', 'italo', 'marisa', 'eunice',
             'wilian', 'kelly', 'tainara', 'alisson', 'iara', 'aparecido', 'israel', 'joelma', 'marinalva', 'edmilson',
             'teresinha', 'rebeca', 'geralda', 'josue', 'cleonice', 'iraci', 'alexandra', 'jenifer', 'mara',
             'elizangela', 'liliane', 'lidia', 'iracema', 'lidiane', 'marilia', 'gerson', 'sheila', 'caua', 'naiara',
             'ines', 'sidnei', 'poliana', 'dalva', 'lurdes', 'emanuel', 'teresa', 'zilda', 'valdeci', 'lucilene',
             'clara', 'rosane', 'jaime', 'valdemar', 'ivonete', 'edivaldo', 'luciane', 'isadora', 'arnaldo', 'lucimar',
             'nilza', 'cristian', 'moacir', 'ismael', 'paloma', 'damiao', 'michel', 'isaias', 'carmem', 'nivaldo',
             'suelen', 'jairo', 'angelo', 'rosimeire', 'jane', 'valdecir', 'wellington', 'alexandro', 'cleusa', 'vanda',
             'ilda', 'denis', 'valdemir', 'eliene', 'wanderson', 'rian', 'claudinei', 'jailson', 'mayara', 'celio',
             'diana', 'sofia', 'yuri', 'denilson', 'ariane', 'iago', 'mariane', 'suzana', 'eder', 'clarice', 'daiana',
             'charles', 'marlon', 'alison', 'eric', 'jonatan', 'edilene', 'elton', 'weslei', 'miriam', 'natanael',
             'erick', 'elisabete', 'eliete', 'karine', 'kauan', 'agnaldo', 'odete', 'jussara', 'izabel', 'luisa',
             'karen', 'odair', 'geovane', 'alana', 'cassia', 'monique', 'catia', 'walter', 'deise', 'isabele',
             'arlindo', 'evelin', 'keila', 'michael', 'adriele', 'andreza', 'joseane', 'alvaro', 'lourdes', 'yasmim',
             'ezequiel', 'everaldo', 'almir', 'alzira', 'nadir', 'carina', 'darci', 'erika', 'ivo', 'ademar',
             'gislaine', 'ramon', 'emily', 'jamile', 'claudete', 'catarina', 'filipe', 'william', 'gessica', 'manuela',
             'jonatas', 'elen', 'geni', 'telma', 'ivanildo', 'romario', 'arlete', 'heloisa', 'valdirene', 'elizete',
             'valquiria', 'jackson', 'eloisa', 'kaua', 'natan', 'gilvan', 'josimar', 'jonathan', 'alfredo', 'juliane',
             'zelia', 'raul', 'dirce', 'emili', 'jandira', 'bernardo', 'gean', 'fabiola', 'carmen', 'estefani',
             'josias', 'rejane', 'rodolfo', 'amelia', 'maira', 'lazaro', 'lucio', 'vilmar', 'anna', 'jefferson',
             'juraci', 'elisa', 'rute', 'alcides', 'luzinete', 'elizabeth', 'iolanda', 'pricila', 'valdomiro',
             'armando', 'cassio', 'romulo', 'ednaldo', 'weliton', 'airton', 'rosalina', 'madalena', 'leidiane',
             'roseane', 'maisa', 'olga', 'camile', 'fabiane', 'emilia', 'claudemir', 'nadia', 'caique', 'marilda',
             'edite', 'welington', 'sirlei', 'paola', 'vivian', 'richard', 'iris', 'nathalia', 'cleuza', 'valdete',
             'lucimara', 'patrick', 'tamara', 'laercio', 'glaucia', 'edmar', 'ligia', 'afonso', 'nubia', 'rose',
             'noemia', 'margarete', 'damiana', 'clovis', 'salete', 'adalberto', 'celina', 'nayara', 'rosiane', 'ivete',
             'jurandir', 'lucineia', 'enzo', 'graziele', 'angelina', 'gloria', 'norma', 'elenice', 'edgar', 'adriane',
             'hilda', 'edimilson', 'iasmin', 'rosilda', 'humberto', 'saulo', 'cauan', 'sidney', 'alexsandro', 'juan',
             'maristela', 'lucineide', 'edinaldo', 'sirlene', 'silmara', 'ruth', 'mariza', 'victoria', 'silvania',
             'jonata', 'itamar', 'lindomar', 'nilda', 'ellen', 'ivani', 'evaldo', 'eli', 'andresa', 'melissa', 'kaique',
             'jeane', 'ari', 'adailton', 'creuza', 'vilson', 'lindalva', 'rosineide', 'jacira', 'divino', 'juarez',
             'cosme', 'gabrieli', 'danieli', 'genivaldo', 'dirceu', 'erik', 'iasmim', 'joyce', 'alaide', 'edina',
             'amilton', 'valdinei', 'josilene', 'andrei', 'judite', 'marinete', 'divina', 'olivia', 'roger', 'lauro',
             'micheli', 'graziela', 'roque', 'dilma', 'karla', 'elena', 'cristiana', 'maura', 'carine', 'jhonatan',
             'diva', 'irani', 'lorival', 'geane', 'vanusa', 'magno', 'rayane', 'leda', 'deivid', 'estela', 'donizete',
             'taiane', 'ivanete', 'robert', 'erivaldo', 'keli', 'marcus', 'virginia', 'carmelita', 'rui', 'wendel',
             'helen', 'samira', 'emanuele', 'milene', 'joelson', 'neli', 'elio', 'altair', 'oscar', 'dayane', 'stefani',
             'zenaide', 'inacio', 'giovanna', 'meire', 'anita', 'isaura', 'jailton', 'isac', 'domingas', 'adelia',
             'geovani', 'frederico', 'laiane', 'heitor', 'marines', 'vanderleia', 'natali', 'isabella', 'quiteria',
             'george', 'sarah', 'bernadete', 'aurea', 'amauri', 'ian', 'danielle', 'romildo', 'ivanilda', 'jesus',
             'josiel', 'kleber', 'kaio', 'levi', 'leonice', 'aldo', 'ane', 'kevin', 'isaque', 'francieli', 'shirley',
             'izabela', 'amarildo', 'edison', 'magda', 'edileuza', 'edimar', 'silas', 'rosemeire', 'marizete',
             'joselia', 'leandra', 'ryan', 'adenilson', 'max', 'tales', 'messias', 'mirela', 'washington', 'alcione',
             'eliza', 'josenildo', 'suely', 'luci', 'salvador', 'fabricia', 'cibele', 'adair', 'elson', 'amaro',
             'socorro', 'doralice', 'soraia', 'eliseu', 'ederson', 'genilson', 'alda', 'raphael', 'tarcisio', 'gilmara',
             'jaine', 'marcilene', 'elizeu', 'irineu', 'zenilda', 'maycon', 'michelle', 'vanderson', 'angelita',
             'adelaide', 'dulce', 'welinton', 'icaro', 'giovani', 'emilly', 'djalma', 'celma', 'ilma', 'valdivino',
             'rosalia', 'silvano', 'manoela', 'eraldo', 'claudineia', 'wallace', 'ione', 'valdeir', 'emile', 'micael',
             'elvira', 'lourival', 'dario', 'talia', 'allan', 'nara', 'gislene', 'lucelia', 'laila', 'jacson',
             'vanilda', 'jucilene', 'adelson', 'adrian', 'dione', 'gilda', 'matilde', 'fagner', 'marluce', 'gleice',
             'evelyn', 'dorival', 'estefane', 'edvan', 'josemar', 'juvenal', 'jaciara', 'neiva', 'ariel', 'kaue',
             'genival', 'ivanir', 'laisa', 'iuri', 'romilda', 'samanta', 'olinda', 'rosimere', 'janice', 'yago',
             'marineide', 'everson', 'ieda', 'beatris', 'edvania', 'lavinia', 'francilene', 'jurema', 'raisa', 'elane',
             'eugenio', 'gelson', 'agenor', 'walace', 'ludimila', 'ilza', 'marilza', 'jardel', 'adelina', 'jadson',
             'graciele', 'josefina', 'shirlei', 'kelvin', 'dalila', 'emanoel', 'adriel', 'ivanilde', 'rosimar',
             'wiliam', 'roni', 'eliel', 'leia', 'ronald', 'noeli', 'isaac', 'naiane', 'giovane', 'getulio', 'abel',
             'josivaldo', 'noemi', 'jennifer', 'caue', 'carolaine', 'marcelino', 'natalina', 'euclides', 'cleidiane',
             'mari', 'yan', 'nazare', 'albertina', 'taisa', 'yara', 'magali', 'aguinaldo', 'karoline', 'darlan',
             'weverton', 'kely', 'maciel', 'wilma', 'larisa', 'edivania', 'expedito', 'clodoaldo', 'enio', 'elvis',
             'aloisio', 'edivan', 'valdelice', 'claudiane', 'creusa', 'jucelia', 'geisa', 'lilia', 'kauane',
             'crislaine', 'tulio', 'marly', 'ednalva', 'adelino', 'rosenilda', 'tadeu', 'cleia', 'anne', 'edinalva',
             'berenice', 'ivana', 'claudionor', 'francine', 'jhonata', 'savio', 'edineia', 'vanuza', 'ludmila',
             'jucelino', 'kamila', 'leni', 'wilton', 'lindinalva', 'rivaldo', 'givaldo', 'valdenir', 'rene', 'carol',
             'susana', 'agata', 'zilma', 'francinete', 'marivaldo', 'kailane', 'alicia', 'guilerme', 'jesica', 'hudson',
             'ariana', 'isabeli', 'leonilda', 'elis', 'zuleide', 'nilva', 'rayssa', 'marciel', 'santa', 'aldair',
             'valdineia', 'oswaldo', 'idalina', 'mercia', 'elder', 'kesia', 'aroldo', 'edilaine', 'kenia', 'maurilio',
             'higor', 'sophia', 'julieta', 'eni', 'pietro', 'rubia', 'jaci', 'marcilio', 'mercedes', 'suelem',
             'stefany', 'adalto', 'doraci', 'marciano', 'cassiano', 'elisabeth', 'ernesto', 'nelci', 'gabrielle',
             'gleison', 'leonor', 'irma', 'otacilio', 'lenir', 'antenor', 'hellen', 'elisete', 'jesse', 'janio',
             'sidinei', 'ademilson', 'rai', 'clarisse', 'thaina', 'guiomar', 'claudiana', 'elcio', 'emilio',
             'givanildo', 'ivaneide', 'cezar', 'thalita', 'abraao']


class Surname(Generator):
    """
    Database for surnames.
    """

    _list = ['abreu', 'aguiar', 'albuquerque', 'almeida', 'alvares', 'alves', 'amorim', 'andrade', 'antunes',
             'aparecida', 'aragão', 'araújo', 'assis', 'azevedo', 'barbosa', 'barros', 'bastos', 'batista', 'bernardes',
             'bezerra', 'bonfim', 'borges', 'botelho', 'braga', 'brito', 'bueno', 'câmara', 'camargo', 'campos',
             'cardoso', 'carmo', 'carvalho', 'casa', 'cassiano', 'castro', 'cavalcante', 'chaves', 'cirino', 'coelho',
             'correia', 'costa', 'coutinho', 'couto', 'cruz', 'cunha', 'dantas', 'dias', 'domingues', 'duarte',
             'esteves', 'fernandes', 'ferreira', 'figueiredo', 'fonseca', 'freitas', 'frota', 'furtado', 'galvão',
             'garcia', 'gomes', 'gonçalves', 'guedes', 'guerra', 'guimarães', 'leão', 'lemos', 'lima', 'lopes',
             'macedo', 'machado', 'maia', 'marques', 'martins', 'mello', 'melo', 'mendes', 'mendonça', 'mesquita',
             'monteiro', 'montenegro', 'moraes', 'moreira', 'moura', 'nascimento', 'neves', 'nogueira', 'novaes',
             'novais', 'nunes', 'oliveira', 'pacheco', 'passos', 'pastor', 'pedrosa', 'peixoto', 'pereira', 'pimenta',
             'pimentel', 'pinto', 'pires', 'queiroz', 'ramos', 'reis', 'ribeiro', 'rios', 'rocha', 'rodrigues', 'sá',
             'sampaio', 'santana', 'santiago', 'santos', 'silva', 'simões', 'siqueira', 'soares', 'sousa', 'souza',
             'tavares', 'teixeira', 'vargas', 'vasconcelos', 'viana', 'vieira']


class Colors(Generator):
    """
    Database for color names.
    """
    _list = ['Água', 'Alizarina', 'Amarelo', 'Âmbar', 'Ameixa', 'Ametista', 'Amêndoa', 'Aspargo', 'Azul', 'Açafrão',
             'Bege', 'Bordô', 'Borgonha', 'Branco', 'Brasil', 'Bronze', 'Caramelo', 'Caqui', 'Cardo', 'Carmesim',
             'Carmim', 'Cenoura', 'Cereja', 'Chocolate', 'Ciano', 'Cinza', 'Cobre', 'Concha', 'Coral', 'Couro', 'Creme',
             'Dainise', 'Dourado', 'Ébano', 'Eminência', 'Escarlate', 'Esmeralda', 'Eucalipto', 'Fandango', 'Feldspato',
             'Ferrugem', 'Flerte', 'Fuligem', 'Fúchsia', 'Grená', 'Gainsboro', 'Glitter', 'Goiaba', 'Herbal',
             'Heliotrópio', 'Índigo', 'Independência', 'Iris', 'Jade', 'Jambo', 'Jasmine', 'Kiwi', 'Kobi', 'Kobicha',
             'Laranja', 'Lavanda', 'Lilás', 'Lima', 'Lemon', 'Linho', 'Madeira', 'Magenta', 'Malva', 'Maná', 'Marfim',
             'Marrom', 'Milho', 'Mocassim', 'Mostarda', 'Naval', 'Neve', 'Nyanza', 'Ocre', 'Oliva', 'Orquídea', 'Ouro',
             'Pardo', 'Prata', 'Preto', 'Pêssego', 'Púrpura', 'Quantum', 'Quartz', 'Rosa', 'Roxo', 'Rútilo', 'Salmão',
             'Siena', 'Sépia', 'Tangerina', 'Terracota', 'Tomate', 'Trigo', 'Triássico', 'Turquesa', 'Ube', 'Urucum',
             'Verde', 'Vermelho', 'Violeta', 'Xanadu', 'Zaffre']
